[features]
seeds = false
skip-lint = false

[programs.localnet]
soltok_escrow = "3pMM6KnPpxc1mhprcPGb7oLLi5skDmcVAvDb4sq4nS1L"

[programs.devnet]
soltok_escrow = "3pMM6KnPpxc1mhprcPGb7oLLi5skDmcVAvDb4sq4nS1L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/arb.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
